### ISSUE TITLE
Page filter performance issues

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#1090]
**Describe the bug**
In a collective with many pages, the page filter in the page list has severe performance issues. For some clients, it freezes the browser for several seconds. Reported with Firefox 121.0 on Linux and with Safari on recent iOS.

**Comment by juliushaertl** [comment]
Did a quick check and it seems mostly time spend on rendering the navigation components when typing, likely because we render all matched ones in sub categories once we start typing in the search.

Not sure what the ideal solution could be, but a quick fix would be to add some debounce, so we at least only filter once when typing a word

**Comment by marcoambrosini** [comment]
The most important thing from a user's perspective is that the input field is frozen when the list is loading. It seems that there's some synchronous logic somewhere tieing the two together. It would be great if it could be decoupled.
