### ISSUE TITLE
Use notify_push for show add / remove of pages

### ISSUE THREAD

**Issue by wargreen** [nextcloud/collectives#1118]
**Is your feature request related to a problem? Please describe.**
When friends add / remove pages, i need to reload to see the change.
This lead multiple-create / remove when working together.

**Describe the solution you'd like**
Use notify_push (the  Client Push app) for live update the list of pages.

**Describe alternatives you've considered**
Use discussion for know when i need F5

**Additional context**
notify_push is used for desktop client sync, deck live update etc... It seem to me that can fluidize the collective workflow.

**Comment by mejo-** [comment]
Dear @wargreen, this is already the case. Apparently the `notify_push` implementation broke with Collectives 2.11.0 due to a bug in `@nextcloud/axios` 2.5.0, but before that version changes to the page list should have get propagated via `notify_push`.

See [`initListenPush` in `Collective.vue`](https://github.com/nextcloud/collectives/blob/1b33d72e50e471febfd61b04188dd77e984fb38c/src/components/Collective.vue#L115) for the frontend part and [`notifyPush()` in `PageService`](https://github.com/nextcloud/collectives/blob/1b33d72e50e471febfd61b04188dd77e984fb38c/lib/Service/PageService.php#L241) for the backend part.

Did you actually test whether this works on your instance? As mentioned, with latest Collectives release (2.11.0) it's broken, but if you still run an older instance, you should see a websocket connection to your notify_push service when loading the Collectives app.

**Comment by mejo-** [comment]
Looking into this again I now understood that synchronization via `notify_push` only works for sessions of the same user so far. So indeed there's more work needed to sync changes between different users.

**Comment by wargreen** [comment]
Yay !
Thank you for all the work !
