### ISSUE TITLE
By creating a collective, all content of an existing folder is deleted

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/collectives#1120]
**Describe the bug**
I wanted to test out collectives and to merge its created markdown files with an existing folder structure.
My folder structure looks like "My_Stuff/1_Projects/".
I've pointed Collectives to the "My_Stuff" folder and created a collective named "1_Projects". As a result, the existing folder was deleted or emptied and a Readme.md file was created -> I lost all of my existing files in the projects folder, which would have been disastrous if weren't just testing things out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change collectives to store its files in an existing folder with content and subfolders
2. Create a collective named after an existing subfolder
3. Wait for all changes to be synchronized
4. The pre-existing content of the folder is gone.

**Expected behavior**
Collectives stores its files in the given folder, without deleting existing files and folder structures.

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 28.0.2
- PHP Version: 8.2
- Database: MariaDB 10.x

**Client details:**
 - OS: Linux
 - Browser: Firefox 122
 - Device: desktop

**Comment by mejo-** [comment]
Dear @rmeissn, thanks for your report. Indeed, when you select an existing folder as mountpoint for your collectives, folders for collectives will be mounted over existing folders if they existed. It doesn't delete the folders existing content but makes it invisible to the user. Changing the collectives folder back to something else (or deleting the collective) should bring back the original content.

Unfortunately there's not much we can do about this. The collective folder mounts are required because the actual content of a collective doesn't live in a users' home directory. It lives in the appdata directory and is mounted into each members' home directory.

**Comment by rmeissn** [comment]
Many thanks for the info!
Then it would probably be good to warn users about this situation, if they select a folder that is not empty.
