### ISSUE TITLE
Links to internal documents should be permalinks (internal shared links)

### ISSUE THREAD

**Issue by Reis-A** [nextcloud/collectives#1152]
currently, (version  2.10.0), fi you add a link with the collectives Link options to a internal document in nextcloud, the added link is in the form  
https://mynextcloud.com/apps/files/?dir=/&openfile=1458015#relPath=//myfolder/myfile.md
if the file is moved with in nextcloud to a different location, the link breaks.

it would be better if it was the permalink of the shared file within nextcloud
https://mynextcloud.com/f/1458015

so the link doesn't break anymore when the file is moved to a different path later.

**Comment by mejo-** [comment]
Dear @Reis-A, thanks for you report. Good news, this got fixed with a revamped link handling in Nextcloud 29. The actual code changes are in Nextcloud Text, not in Collectives, though. Here's the relevant PR: https://github.com/nextcloud/text/pull/5412

Due to the complex nature of the link handling changes, they will not get backported to Nextcloud versions below 29 unfortunately.
