### ISSUE TITLE
Sharing a collective with the "everyone" group is not working

### ISSUE THREAD

**Issue by M-tp** [nextcloud/collectives#1202]
Sharing a collective with the "everyone" group in Nextcloud is possible, but it is not working. The shared collective does not show on the users' collective tab.

**Comment by mejo-** [comment]
Dear @M-tp could you elaborate what you mean with the "everyone" group? I guess that's a group that is manually maintained on your instance. To my knowledge there's no such thing as a group covering all users on Nextcloud :thinking:

**Comment by M-tp** [comment]
Hi @mejo- it's a function offered as Nextcloud app: https://apps.nextcloud.com/apps/group_everyone

**Comment by mejo-** [comment]
Ah, I see. So with this app the problem is that the Nextcloud teams/circles app doesn't know about all the users that existed before the app got installed. New users that got created *after* the app got installed should see the collective, right?

The following command will let the circles app re-sync all groups and their members, which should solve the problem for you. You only have to run it once, as new users will get synced automatically once they're created:

```
occ circles:sync --groups
```

Please let me know if this helps, then I can add documentation about it.

**Comment by bilias** [comment]
> `occ circles:sync --groups`

Why is this needed? It supposed to do it upon login.
See screenshot
![auto_groups](https://github.com/nextcloud/collectives/assets/47315739/bd67d8fa-b225-44e0-b5e5-51ba791fff1a)

**Comment by mejo-** [comment]
>  I have to unshare/reshare the folder every time a new user comes in.

What do you mean with unshare/reshare? This issue was about adding the `everyone` group to a collective as member. Do you mean to share a folder? That sounds unrelated to collectives :thinking: 

The command `occ circles:sync --groups` needs to be called once after the `group_everyone` app was installed to register existing users as group members to circles/teams. Afterwards, this should happen automatically when adding a new user.
