### ISSUE TITLE
Allow to use this app without circles installed

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#127]
In GitLab by @szaimen on Mar 8, 2021, 02:11

Hi, 

I'd really like to use this cool app but with system groups (admin managed) so that I'm not forced to install the circles app. Do you think that such a feature is feasible?

Cheers!

**Comment by jotoeri** [comment]
Hey @mejo-,

I'd also really like to use the collectives app instead of the Notes app for some kind of wiki on our club-instance. On that instance, we manage groups for several youth-groups. I'm fine meanwhile with having the circles app active in the background as provider for collectives. But i don't want to activate the contacts app, since we just don't need the contacts functionality, it will just add confusion to the cloud usage and users will start creating their own circles instad of coming back to us for administration of the groups. And i really want to keep this cloud as clean and structured as possible.

Thus - I just thought about adding a modal (Or just content into the existing modal) in the collective-settings to query the circles api from there if the contacts app is not available. Most probably with limited functionality, but just such that collectives is usable without another (frontend) app installed. -> Would you be fine with such an ansatz? So is it worth to dig into? 😉 

Greets,
Jonas

**Comment by mejo-** [comment]
Hey @jotoeri, thanks for your feedback. We're already working on building some basic membership management directly into the collectives app (see PR #464) - and you have good point that we should get rid of the warning on missing Contacts app once it's there.
