### ISSUE TITLE
Navigation bar and navigation bar toggle doesn't work since 2.11 

### ISSUE THREAD

**Issue by rrouvreau** [nextcloud/collectives#1289]
**Describe the bug**
When opening Collectives, the collective navigation bar doesn't show and stays in "loading state" with flashing grey items. The toggle button to hide or show collective navigation bar has no effect. This bug is the same on Collectives app landing page with the button "New Collective" or when opening a collective directly using the url. 
The collective page navigation bar seems to work properly.
A few time the collectives list appear when opening the Collectives App but the toggle button is still not working and this occurence is rare
**To Reproduce**
1. Update collectives to version 2.11
2. Click on Collectives or open a collectives using its url

**Expected behavior**

**Screenshots**
![image](https://github.com/nextcloud/collectives/assets/170700599/d74f7ffc-6a16-473c-b41c-359bcf4bd63e)

![image](https://github.com/nextcloud/collectives/assets/170700599/d80a3639-f1ca-45f6-af2f-aeaaaa03a82a)

**Server details:**
- Collectives app version: 2.11
- Nextcloud version: 28.0.5, same bug with last night update to 28.0.6 and 29.0.1
- PHP Version: 8.2
- Database: MySQL 8.0

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Browser version: 126.0
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Zero error showing in the logs
```

#### Browser log
```
TypeError: e.trashCollectives.sort is not a function
    trashCollectives collectives.js:101
    t vuex.esm.js:881
    n vuex.esm.js:140
    VueJS 3
        get
        evaluate
        Na
    get vuex.esm.js:671
    a vuex.esm.js:1026
    VueJS 3
        get
        evaluate
        Na
    displayTrash Navigation.vue:81
    VueJS 3
        get
        evaluate
        Na
    fn Navigation.vue:1
    VueJS 2
        i
        xt
    _d NcAppNavigation-DjlepJn1.mjs:126
    VueJS 7
        _render
        a
        get
        run
        na
        yn
        _n
vue.runtime.esm.js:3065:16
```
</details>

**Comment by mejo-** [comment]
Thanks for your report @rrouvreau. I'll post some technical findings here while trying to debug this issues:

- For some reason, [`findTrashByCircleIdsAndUser()`](https://github.com/nextcloud/collectives/blob/5b73b2dfb6f2ac4ed50b4fc893b5b4a6d0c1bbd9/lib/Db/CollectiveMapper.php#L111) returns an associative array in some situations.
- [Since version 2.11.0 we return this array directly instead of building a new one](https://github.com/nextcloud/collectives/commit/1c7d1956cee227b2c1fa8df248249d3874927449#diff-34de32afbba8f1c2c5c8ee8d12adfb7440be1d546931012053cf65bfa5f9763bL28-R38). That's why the bug appears since version 2.11.0 on some instance.
- My user suffers from the same bug on our company instance, but I'm unable to reproduce it locally (both on server versions stable29 and master), and I also failed to reproduce it on other productive instances with 28.0.5.
