### ISSUE TITLE
Ownership of collectives

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/collectives#1380]
Can I see, who the owner of a collective is? 
Can I transfer a collective to another user?

We use collectives as a company knowledge base. It would be bad if parts of it were lost, when a person leaves the company and I delete the account. But I can't even see who owns which collectives. 

So I need and administrative function that shows me, which collectives exist in which account, and that makes it possible to transfer them from one account to another.

**Comment by nerrehmit** [comment]
We have exactly the same use case.
Additionally we would like a way for an administrator to manage existing collectives from a members/moderators/owners perspective.

Have you found a way to manage members from an admin account? I don't want a case where a team or a couple persons start using a collective and then the only admin of that collective is on holiday/ absence while the others urgently need new members added or something similar.

**Comment by kaffeeringe** [comment]
It would be cool if there were private and shared collectives. When you create a new collective you are asked if it should be private or shared.

A private collective is owned by the user and it can't be shared. 

A shared collective belongs to a functional account. And is automatically shared with the user who created it. 

As a background: I created an extra account that only shares all resssources that are owned and shared by our organisation, so that there's no problem when a person leaves the company. 

But essantially this is a core problem of Nextcloud: How does an organisation provide ressources? How do I set up a Nextcloud so that it is no problem, when a person leaves the organisation? What is the intended way?

**Comment by mejo-** [comment]
Dear @kaffeeringe and @nerrehmit,

collective ownership is a core principle of Collectives. A collective isn't owned by a particular user. Its data lives in the `appdata` directory and is mounted into the home directories of all its members. In other words, you don't have to fear that a collective becomes unavailable because a particular account gets deleted.

Just make sure that each collective has more than one admin configured (in the member settings).

Collectives uses circles/teams to manage memberships. You can list all the circles on your instance via `occ circles:manage:list`. Watch out for circles with config flag `["A"]` (which stands for "app-managed". These probably are the circles that belong to a collective.

You can also add/remove members from circles using the `occ circles:members:...` subcommands.

I hope this helps.

**Comment by kaffeeringe** [comment]
Interesting! Thank you for the clarification!
