### ISSUE TITLE
Read only page content sometimes outdated

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/collectives#1437]
We have seen some reports that the read only rendering of a page is sometimes outdated. There are no clear steps to reproduce this yet, though a few interesting aspects:

- Reloading the page does still show the old content
- Switching back to edit mode has the new content in place
- Using a different browser also shows the new content in read only mode

There is a [video](https://cloud.nextcloud.com/f/10239518) of it shared by Fabrice in our chat

**Comment by juliushaertl** [comment]
Sometimes there seems to be a cached webdav GET in firefox but reports were around Chrome and I haven't managed to see that locally

![image](https://github.com/user-attachments/assets/f72eb6cf-3de9-40f8-a945-afba9b797c1d)

**Comment by juliushaertl** [comment]
I managed to reproduce this again on our company instance, also checking and even after a reload the Readme.md request was cached.

@mejo- Could you please check that? Maybe we just need a cachebuster on the webdav URL to make sure it is always updated if the content changed

**Comment by juliushaertl** [comment]
Steps taken so far to reproduce this for me:
- Browser caching enabled
- Edit a page, paste something into it
- Switch to another page relatively quick
- Switch back to the originally edited page

**Comment by mejo-** [comment]
Debugging revealed two things:

1. Collectives doesn't update the reader content with the editor content at initial load. https://github.com/nextcloud/text/pull/6274 will help with that.
2. The DAV request that is supposed to fetch the file content doesn't go out on Firefox, probably because it thinks that it already has it cached. This is not reproducible on Chromium, so I suspect a bug in Firefox cache handling.

In any case, adding a cache buster parameter to the DAV request seems sensible, as we always want to get the latest DAV content and don't want anybody to cache this for us.

**Comment by mejo-** [comment]
@juliushaertl I also checked if reverting https://github.com/nextcloud/server/pull/46320 changes anything here, it does not.
