### ISSUE TITLE
Improve user management with a growing number of collectives

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#244]
In GitLab by @larsbecker on Sep 17, 2021, 18:48

Since we begun evaluating collectives with more users it occurred to us, that the user management is quite uncomfortable with a growing number of collectives. This is because there's a hard relation between collectives and circles. I think this dependency doesn't make much sense and it would be much better to allow to configure the circles (and possibly groups) which have access to the collective, so that there is effectively a n:m relationship. 

This would ease user management and help to reduce the circles and the need to enter many users again and again.

**Comment by mejo-** [comment]
@larsbecker we started to implement user management inside the Collectives app. For now, you will be able to select members in the dialog for a new collective, but we plan to have a dialog for adding and removing members from existing collectives later on.

Given that this hides the complexity of "collective <-> circle" from users, would this solve this issue for you? Admins could just add circles to collectives without having to care about the fact that the collective always has an "owner circle" itself.

**Comment by lars-becker** [comment]
> Given that this hides the complexity of "collective <-> circle" from users, would this solve this issue for you? Admins could just add circles to collectives without having to care about the fact that the collective always has an "owner circle" itself.

That certainly would help with user management. I still don't like the fact, that there needs to be an owning circle because this seems somewhat redundant in some use cases (such as having three different collectives which share the same user group, e.g. an ngo board, that needs to access it), but you surely could argue that this is a subjective aesthetic preference for not populating the circle index with unnecessary circles.  I guess in praxi this won't hurt. Thanks!
