### ISSUE TITLE
Feature: Add support for BPMN (Business Process Model and Notation) diagrams

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#292]
In GitLab by @roland.kirst on Feb 23, 2022, 12:28

BPMN is the standard for describe business processes and is also as plugin available. This is good and easy way to describe business processes inside documentations and it will be great to have it.

Link: https://www.omg.org/spec/BPMN/

**Comment by suntorytimed** [comment]
Mermaid diagrams wouldn't solve this request. For BPMN diagrams it would be ideal to be able to show .bpmn files in the Collective. The mentioned Nextcloud app does this in a really good way via bpmn-js. I guess Nextcloud Text would have to support iframe embedding or something similar, which doesn't sound like a good idea for a markdown based knowledge base. Maybe it would be good to link to the files in Nextcloud in an easy way or be able to create a BPMN file instead of a new page.

**Comment by max-nextcloud** [comment]
I would like to stay away from implementing support for specific file types in collectives. There's various ways to achieve support for it never the less:
* Register a viewer handler for the file type. Then you can link to the file and it will open in the viewer
* Extend text to support viewing the content like it does with mermaid.

The first would happen in its own app, the second in the text app or an extension for it.
