### ISSUE TITLE
Allow to remove the emoji of a page

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#422]
In GitLab by @narF_narF on Nov 8, 2022, 15:13

Currently, it's impossible to remove an emoji after it has been set. It would be nice to allow the user to undo its change.

Steps to reproduce:
1. create a page in a Collective
2. assign an emoji to the page

Current result: There are no way to remove the emoji
Expected result: The user can remove the emoji

Note: While it's possible to assign a different emoji, it's not possible to get rid of it entirely

Suggestions:
1. Add a button in the emoji picker to remove the emoji
2. While the emoji picker is open, pressing Delete or Backspace on your keyboard will also get rid of the emoji

**Comment by narFnarF** [comment]
In the meantime, you could detect if the user presses Esc or Del or Backspace on the keyboard while the emoji picker is open, and remove the emoji. It's not ideal because it's hidden and not touch-devices friendly, but it's at least better than the status quo.

Another option would be to display a delete button only when mouse over the emoji. You could even use the ⛔ emoji for that button! 😋 
[](https://i.imgur.com/m9bJ6vl.png)

The note app _Joplin_ moved the emoji picker inside the popup when editing the name of a notebook:
![](https://i.imgur.com/MrjnrC4.png)
Maybe Collectives could display the ⛔ button on the emoji picker when the cursor is inside the title textbox? This way, it would let users on touch devices be able to remove the emoji.

I have more ideas if you're interested.

**Comment by narFnarF** [comment]
For anyone reading this and looking for a solution on how to remove an emoji, a workaround is to go in the File app and locate the file of the Collective page, and then duplicate that file. The copy will not have the emoji. (The downside is that it will break links to that page, if any)

**Comment by Snafu** [comment]
Hello,
I'm facing the same issue as @narFnarF and would like to request some kind of fix as well.

> Sure. We use an external javascript library as emoji picker. Unfortunately, until now, this picker doesn't support to select an "empty emoji". I now went ahead and opened a feature request against the upstream project: [serebrov/emoji-mart-vue#253](https://github.com/serebrov/emoji-mart-vue/issues/253)
> 
> Adding an own action "Remove emoji" would be a bit too heavy and clutter the actions menu in my eyes.
I have to disagree here. As you correctly state, you are using an external library for picking an emoji. Once you pick this emoji, the picker somehow returns the emoji picked for futher use. However, this has nothing to do with how this emoji is then used later on. In my opinion the emoji picker project doesn't need to be changed at all, but the way it is used needs to be changed.
The flaw is that Collectives allows you to choose an emoji, then displays it next to the title but there is no way to clear that emoji.
A more traditional use case of the emoji picker would be a text box, there you click the picker, choose your emoji and it gets iserted at the cursor position. If you don't like the emoji, you can delete it with the backspace key. This operation is not possible though in Collectives, because apparently the only interface to that emoji field is the picker. Maybe you could add that if you hit backspace at the beginning of the title input, it clears the emoji (or gives a popup "do you want to clear the emoji?"). Or add a menu that shows up when you do a right mouse click. Alternatively the popup like in Joplin would also be OK in my mind.

I have to agree again with narF_narF that it is currently bad user interface design in Collectives. For an irreversible action, I too would expect a warning popup before I commit to the action. Picking an emoji shouldn't be an irreversiable action, though. Like narF_narF I was facing the issue of the odd one out in the overview of pages. I ended up creating a new page, copying the content of the old page and deleting the old page.

**Comment by niklas-englert** [comment]
@mejo- I request this issue to be marked as a [bug](https://github.com/nextcloud/collectives/issues?q=is%3Aissue+is%3Aopen+label%3Abug) not an [enhancement](https://github.com/nextcloud/collectives/labels/enhancement) as this renders the main feature of supporting icons on collective pages unstable due to inconsistencies.

**Comment by arnowelzel** [comment]
I also agree that this should be considered a bug. Since the default for new pages is no having an emoji at all it should be possible to remove the emoji again after you have selected one.

Another suggestion: if it is not (easily) possible to remove emojis - why not just set a default emoji for new collectives and pages? Then even the behaviour would make more sense. There is a default emoji but you can change that if you like. Since pages will already be represented by a default icon in the navigation tree, using an emoji like 📄 (`:page_facing_up:`) would be a good alternative as default emoji. Or maybe even let the user decide what default emoji to use for new documents in the collective settings (maybe in the page settings of the collective).

You might also update existing documents in the database during an app update, so those documents which have current no emoji yet, (`NULL`) will get updated (and if the collectives get a new setting for the default emoji of new pages that would have to be set as well of course):

```
update oc_collectives set emoji = '📄' where emoji is NULL;
update oc_collectives_pages set emoji = '📄' where emoji is NULL;
```

**Comment by max-nextcloud** [comment]
The upstream library we use provides an extension now that makes this possible:
https://github.com/serebrov/emoji-mart-vue/issues/253#issuecomment-1585978632

We will need to make this available in  vue-nextcloud first before we can use it here.

**Comment by max-nextcloud** [comment]
Nextcloud vue ships the ability to unset an emoji from 7.12.2 on: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4409

So we need to upgrade and then toggle that feature on where needed.
