### ISSUE TITLE
Allow restoring a deleted page

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#47]
After deleting a page we should allow restoring it.

**Comment by marcotrevisan** [comment]
Yesterday a colleague deleted the whole contents of a collective (leaving only the root Collective existing, but empty), because of a misteke in using his webdav Files client.
I was luckily able to spot it by checking the web server logs, where I found the recursive DELETEs. Otherwise I would have said it "misteriously disappeared".
As you know Collectives are available via Webdav for client side editing too (no Collectives UI is protecting them).

For this reason in my humble opinion a trashbin is an expected feature. Mistakes in deletion can happen without the user even being aware of it.
Alternatively, an option to decide wether or not Collectives may show up in Files should do.... not sure how many people really use them in Files or via webdav client. Even the page in Files is suggesting the user not to use it.

Hope this helps in your decisions. 
Thanks and Regards

**Comment by mejo-** [comment]
Thanks for your feedback @marinkaltani, much appreciated! We're currently working on a collective-wide trashbin for deleted pages.
