### ISSUE TITLE
Allow mounting collectives inside subfolders

### ISSUE THREAD

**Issue by paulcalabro** [nextcloud/collectives#514]
**Is your feature request related to a problem? Please describe.**

I'd like to store data within a nested folder, like I do with other apps.
My existing folder resides in an app folder within another folder for remote S3 data.
But this results in:
> "Invalid path selected. Only folders on first level are supported."

**Describe the solution you'd like**
I'd like a consistent experience where I can store data in an arbitrary folder location.

**Describe alternatives you've considered**
I don't think there's an alternative solution that allows for me to easily organize my data in a flexible manner.

**Additional context**

Similar apps that currently allow this:

<img width="328" alt="Screenshot 2023-01-23 091025" src="https://user-images.githubusercontent.com/585059/214089743-5826a3e6-fd75-4ffa-8059-e2676be3ed65.png">

**Comment by max-nextcloud** [comment]
@paulcalabro The folder currently only serves to add the mount points of the collective folders. Since different users share a collective the data is also stored in a shared location.
So even if you could move the folder into the S3 folder it would be empty in S3 and the data would still reside in the appdata folder.

If you want to put the data of collectives into an S3 storage it would be more interesting to see if folders inside appdata can reside in an external storage.
If you want to only use this as a single user the `Notes` app might be a better fit.
