### ISSUE TITLE
Allow deactivation of URL previews

### ISSUE THREAD

**Issue by matthiastaeschner** [nextcloud/collectives#579]
**Is your feature request related to a problem? Please describe.**
Currently, for any URL put to a MD file in a collective a preview is automatically created and added and there's no way to deactivate this behavior. This, on the one hand, heavily bloats the content of the pages and makes them more difficult to read. On the other hand, such an automatic loading from remote content may be a privacy / security risk, too.

**Describe the solution you'd like**
Allow the activation / deactivation of URL previews in the WebUI for each collective or all collectives at once.

**Describe alternatives you've considered**
Check for the `reference_opengraph` config parameter and don't show loading spinners for the preview if the config parameter is set to `false`.

**Additional context**
Currently, there's the possibility to deactivate the loading of remote content via the `reference_opengraph` config parameter on system level. But this only adds a permanent loading spinner instead the remote content.
Related issue on Nextcloud server level: https://github.com/nextcloud/server/issues/35840

**Comment by max-nextcloud** [comment]
https://github.com/nextcloud/text/issues/3588 is the corresponding issue in text. I think we should remove the loading spinner there and that would also cover this one.

@matthiastaeschner Would you need this setting to be specific to collectives or would it be enough if it was also affecting text and other apps using text for editing content?

**Comment by matthiastaeschner** [comment]
@max-nextcloud Thanks for your reply. As a first solution it would be enough to have this global solution for text and apps using it: checking for the `reference_opengraph` config parameter and don't try to load a preview (show loading spinner) if the config parameter is set to `false`.

Having an app-wise (or even collective-wise) option in the WebUI to switch this on and of would be really nice, though.

**Comment by max-nextcloud** [comment]
I thought about this some more and since we expose the collectives md files in the files app just restricting this in collectives would not be sufficient. If someone opens the same document in the text app in files it would still have the link previews and leak the metadata.

So I think this has to be a server wide setting. I can't think of a meaningful scope to limit this to. If we said we restrict it for all files in a given folder - say the folder of a collective - it would break once a single file is shared on its own as the share will show up on the top level for the recipient.

I'll close this and reopen the text one to get rid of the loading indicator. If you can think of a way to scope this consistently please let me know and feel free to reopen.

**Comment by max-nextcloud** [comment]
Created https://github.com/nextcloud/text/issues/3824 to track the loading indicator issue

**Comment by Mannshoch** [comment]
I deactivated as described in https://github.com/nextcloud/text/issues/3588#issuecomment-1358355490 But now I have strange blanks in the middle of some text. 

currently, I have a numbered List. The list entries are linked to some Nextcloud resources and links to outside. The numbered List now contains a lot of blank spaces. 

Is it possible to get rid of this?

**Comment by Mannshoch** [comment]
Are youn not able to recreate it? Whaat problem did you have?

**Comment by arnowelzel** [comment]
> I deactivated as described in [nextcloud/text#3588 (comment)](https://github.com/nextcloud/text/issues/3588#issuecomment-1358355490) But now I have strange blanks in the middle of some text.
> 
> currently, I have a numbered List. The list entries are linked to some Nextcloud resources and links to outside. The numbered List now contains a lot of blank spaces.
> 
> Is it possible to get rid of this?

Maybe that helps you: https://github.com/nextcloud/server/issues/35840#issuecomment-1676504721

**Comment by Mannshoch** [comment]
@arnowelzel Thanks! Yes that helps.

**Comment by kartoffelheinz** [comment]
Not sure why this has been closed, the reference_opengraph parameter does not work in latest Nextcloud versions. Any URL e.g. in deck card descriptions or the likes will still get previewed. So annoying. What can I do to disable this useless (and security and privacy related ultra risky) feature once and for all?

**Comment by mejo-** [comment]
Dear @kartoffelheinz. With Nextcloud 29 link handling in Text and Collectives will receive a big overhaul.

Clicking on a link will no longer open it straight away because that prevents you from editing the link in an accessible way. Instead, it will open a link bubble. From there you can either open the link target or edit the link that you clicked.

For standalone links (paragraphs that only contain one link) we'll also introduce the possibility to configure (for each link separately) whether you want to display a preview in the document (as it is now) or whether it should be displayed as a text link only.

I hope that will help your usecase.

If you're sure that the `reference_opengraph` parameter doesn't work, that's a bug though. Please report it against https://github.com/nextcloud/server
