### ISSUE TITLE
Always open most recent collective and page

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#75]
Instead of opening the EmptyPage when entering the app, we should open the most recently used collective.

Even better, open the most recently opened page from the most recently opened collective.

A startpage (#69) would still be helpful for users that enter a collective for the first time.

**Comment by mejo-** [comment]
After briefly discussing this again with @max-nextcloud I think that we're not going to implement this anytime soon. Other apps don't do such a thing either. A dashboard widget (#113) would be the better solution for a shortcut to recent collectives and pages.

**Comment by mschmidm** [comment]
I would also appreciate this feature as we also have only one collective on our instance. A dashboard widget is not an option for us as we do not use the dashboard. The simplest and most intuitive solution for our use case would be to open our single collective by default. Since the feature is clearly useful for this (probably not so rare) use case and could be optionally configured by the admin, I see no reason not to consider this feature.
Besides all, thank you for your work! I love Collectives and would love to see that feature come :)
