### ISSUE TITLE
Link to a folder on Nextcloud only works in "Edit" mode

### ISSUE THREAD

**Issue by perkm** [nextcloud/collectives#844]
**Describe the bug**
When linking to a folder in Nextcloud, there is only a loading circle shown in the middle of the screen.

The link works in "edit" mode

**To Reproduce**
1. Create a new collective
2. Click on the "Insert link" button and select "Link to file or folder" 
3. Select any folder on Nextcloud and click on "Choose"
4. Click on "Done" to save the collective
5. Click on the link that was just created
6. A loading circle appears in the middle of the window

**Expected behavior**
Link should open the desired folder on Nextcloud

**Screenshots**
![Screenshot 2023-08-23 at 14 08 49](https://github.com/nextcloud/collectives/assets/84352462/5a600163-4551-46e9-b9cb-364570b6ae3a)

**Client details:**
 - OS: OSX and Windows tested
 - Browser: Chrome, Safari, Firefox
 - Device: Macbook

<details>
<summary>Server details</summary>

**Collectives app version:** 2.7.0

**Operating system:** Ubuntu 22.04 LTS

**Nextcloud version:** 27.0.1 running on Docker

</details>

<details>
<summary>Logs</summary>

#### Browser log
```
Viewer.vue:545 Could not open file /test/test_folder_20221013/ TypeError: Cannot read properties of undefined (reading 'split')
    at a.openFileInfo (Viewer.vue:568:1)
    at a.openFile (Viewer.vue:538:1)
```

</details>

**Comment by mejo-** [comment]
This is fixed in the upcoming Nextcloud 29 release thanks to the new link bubble feature in Nextcloud Text.

**Comment by osm-frasch** [comment]
**I have exactly the same behaviour.** 
My Nexctloud version is 28.0.4

**Why will this problem only be solved in 29?**

As a company, we tend to wait a little longer to upgrade? I praised knowledge management via the Collective app just a few weeks ago. Now I see that essential things are not working.

**Comment by mejo-** [comment]
> Why will this problem only be solved in 29?

Dear @osm-frasch,

this is because in Nextcloud 29 the link handling in the Text app (which is the editor used in Collectives) got refactored. As a side-effect it fixed this issue. I understand that this seems frustrating to you. You can rest assured that we try our best to backport bugfixes to point releases of all supported Nextcloud versions - but this fix was part of a major revamp which we simply cannot backport.

**Comment by osm-frasch** [comment]
@mejo- 
OK, I understand that! Sorry. 
It would make sense to communicate something like this officially in the future. Perhaps in the app descriptions in the app store. I already had a big functional problem with collectives when I wanted to introduce it. Now, unfortunately, I have to back out again because the links are really necessary. It could be another 3 to 4 months before we upgrade to 29

**Comment by mejo-** [comment]
@osm-frasch if your company relies on Nextcloud, I suggest to buy an enterprise subscription that covers the Collectives app. That's a perfect example where an enterprise subscription would help :relaxed:
