### ISSUE TITLE
please take this into consideration

### ISSUE THREAD

**Issue by punkyard** [nextcloud/collectives#920]
hi again

the new features at the top of the page is leading us to stop using Collectives
in a public page - this feature makes no sense
there is no way to hide them
These features appeared with severe bugs in our instance

<img width="392" alt="Capture d’écran 2023-10-02 à 08 30 37" src="https://github.com/nextcloud/collectives/assets/59349105/b64144a7-58e0-4033-b78d-ea61f0e7a587">

Please, remove the band at the bottom of the page in public mode
it hides the text and brings no information as the domain can be seen in the address bar, and also the logo
(here we can read "notre.rez")
<img width="305" alt="Capture d’écran 2023-10-04 à 00 40 28" src="https://github.com/nextcloud/collectives/assets/59349105/c03ccb86-8191-4d29-97c6-4a4d3c5988ed">

please add a 'copy link' option for public shares for every page roll down menu
<img width="393" alt="Capture d’écran 2023-10-02 à 09 00 49" src="https://github.com/nextcloud/collectives/assets/59349105/eee42c4f-5c22-49d5-be8e-331d0c94b616">

Hope you'll hear us
thank you

**Comment by max-nextcloud** [comment]
Hi @punkyard 

Thanks for your feedback.

It's easier for us to address the issues in question if you split the issues by topic and provide a concrete summary as the title.

I think the first points has already been reported in #835 and addressed in #894. Or am I missing something.

Please create separate issues for the remaining aspects so we can address them one by one.

Thanks!

**Comment by punkyard** [comment]
thanks @max-nextcloud 
I have the feeling that i'm not hea😅rd about this. So I repeat it.
Collectives give a public display of the content, and it doesn't seem optimum.. to me 

Somewhere, I guess, people meet and make decisions that really change other users' experience.
Do you know how can I participate to the evolution of the ergonomic in NC?

**Comment by mejo-** [comment]
Dear @punkyard,

>  I have the feeling that i'm not hea😅rd about this. So I repeat it.

you may rest assured that we read all Github issues and comments :wink: But we only have so much time and cannot react to everything immediately.

> Somewhere, I guess, people meet and make decisions that really change other users' experience.
> Do you know how can I participate to the evolution of the ergonomic in NC?

For sure, there's a team of developers that maintain and drive forward the software. Some parts of Nextcloud are mainly maintained by the Nextcloud GmbH and its developers, some parts are solely maintained by community members.

Decisions that concern the user interface (UI) are usually discussed with the Nextcloud Design Team first. The team helps us developers to take decisions on how to design the user interface, taking into account accessibility, varying needs of different user groups and so on. In general we try our best to keep the UI accessible and intuitive for novice and non-technical users. Some decisions might be controversial. We're always happy about feedback, but rest assured that none of them is taken lightly.

Regarding your concerns about the recent pages widget: with the latest Collectives releases you're able to collapse it by clicking on the "Recent pages" caption. We will not turn it off (or make it collapsible by default) though because we strongly believe (and get the feedback) that the overview over recent changes is helpful to people who open a collective occasionally.

**Comment by punkyard** [comment]
hey @mejo- 
thanks a lot for this lovely message : ) you took the time to read and answer which I truly appreciate :)
I wish I could enter this realm of thinkers and defend other points of views ^^

Reading your answer gives us a precise point of view, thank you! : there will be no turning back and Collectives is going to keep those recent add-ons.
I guess we won't probably be using Collectives in the future as it has lost its simple public interface as we have enjoyed it on a daily basis for the past year 👍 All these improvements are disturbing the reading of our web-visitors/readers who are external to our organisations.

thanks again for your concern

**Comment by mejo-** [comment]
@punkyard to better understand your problem: what's the problem with the recent pages widget for external readers? After all it just lists the pages with latest changes, no?

Also, would the ability to publically share single pages with their subpages (instead of just the whole collective) help you?

**Comment by punkyard** [comment]
well, external readers will read Collectives once in a while.
Instead of being welcomed by text we had prepared, they found links, bog emojis, list of users..
That's not why they came here for
That's not why we made the Collective public

In Edit mode, why not 
WE don't like - but why not

I think we have heaps of tools to mention and discuss which collectives had been modified - strating with sorting by:
- created date
- last modified date !!
- personal sorting
- alphabetical and anti-betical sorting !!

Collectives public share is like a web site
with a slogan, it's a welcome page
Now it looks like .. well, I cant compare ..

Please, remove these add-ons from public share
and move them to the left panel in the edit mode

`would the ability to publically share single pages with their subpages (instead of just the whole collective) help you?`

i'm not sure I understand your suggestion. We wanted an access to the public link of a page.
Instead, we had to :
- go to the menu of the collective
- click the public link
- open new tab
- paste public link of the collective
- navigate to the page we want to share
- copy the url from the url field of the web browser
- close the tab
- come back to the collective we are editing or the email we are writing to paste the public link of that page we wanted!
.. see?

thank you very much @mejo- for your concern

regards ✌️
