### ISSUE TITLE
Smart picker should use page title for links to other pages within collective

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/collectives#949]
**Is your feature request related to a problem? Please describe.**
1. enter page edit mode
2. open smart picker with '/'
3. select collective page
4. search for a page 
5. select page
6. this generates a link. Text is "https://cloud.example.com/collectives/Demo/Page?fileId=12345"

**Describe the solution you'd like**
the generated link text should be  "page title"

**Describe alternatives you've considered**
1. write the page title 
2. mark text
3. use insert link, instead of smart picker

**Comment by Gielovic** [comment]
Agree that this would greatly enhance readability and allow for a more 'wiki' style documentation. Being able to easily 'edit' the display text via the editor, the same way as you would update the URL, could also be an option, even to adapt the generated 'page title' display text.

**Comment by mejo-** [comment]
In future, the smart picker will insert the link as preview straight away. This is tracked in https://github.com/nextcloud/text/issues/5838.

**Comment by NikoKS** [comment]
@mejo- , is this future already implemented? https://github.com/nextcloud/text/issues/5838 seems to be closed also.

**Comment by mejo-** [comment]
@NikoKS it's implemented in Nextcloud Text development branch but unfortunately didn't make it into the upcoming Nextcloud 29.0.4 release in time. So it will become part of the Nextcloud 29.0.5 release scheduled for August 20th.

**Comment by NikoKS** [comment]
Hello @mejo-, just tried the update today. Apparently, it's quite different to the request made in this issue page. In my opinion, it makes much more sense to show the link as the title page when a link to another collective page is added. Especially when adding the link in a middle of a sentence.

This would make a much better experience of connected notes similar to a wiki page. For example, It would be nice to have a link to https://github.com/nextcloud/text/issues/5838 in the middle of a sentence instead of a preview to that page in a new line.

Is it possible to reconsider the request in this issue?

**Comment by timkrief** [comment]
@NikoKS I made this new issue that is really similar: https://github.com/nextcloud/collectives/issues/1583

**Comment by timkrief** [comment]
Ok, I tried it, and it doesn't place the page name, it creates a link preview... it's really not what was described in this issue, and I think it should be re-opened.
