### ISSUE TITLE
Do not create attachment copy of images already in the collective

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/collectives#950]
**Is your feature request related to a problem? Please describe.**
1. create collective
2. create two pages "overview" and "details"
3. copy an image into the collectives folder (for example with the files app)
4.  insert image from step 3. into "overview"
5.  insert image from step 3. into "details"
6. now we have three copies of the image: the original and two attachments

issues:
  * changes to the original will not propagate to "overview" and "details" page
  * additional (unintended) use of storage space

**Describe the solution you'd like**
* if the images is already in the collective, do not use attachment, link to the image file
* make sure the link is permanent (moving the page and/or the image should not break the link)

ideally no copy is created for any file hosted on the same Nextcloud instance, but this might be difficult to implement, because of permissions and the fact that files-app has no link to collectives and changes done with files-app could break the collectives page.

**Describe alternatives you've considered**
* edit the md-file and remove the attachment folders

**Comment by mejo-** [comment]
Dear @schaarsc, thanks for your report. When adding proper attachments support to Text and Collectives we thought quite a bit about your concern and finally decided on purpose to always store a local copy of the file when adding an attachment.

The strongest argument was the problem of accessibility. When you insert a file from your Nextcloud instance and then share the text document with others, or add other members to the collective, the inserted file might not be accessible to them, because it's not part of the same share and lives in your personal home folder. That's not what users expect.

Another argument is that source files might get moved away or deleted.

If you want to reference a file from your Nextcloud and don't want it to be copied, linking to it probably is the best thing you can do. With link previews you should even see a preview of the file/image in the collectives page.

I'll close the issue as not planned because we have not desire to change the current behaviour. Still please don't hesitate to comment with your thoughts if you'd like to further discuss this.

**Comment by schaarsc** [comment]
Dear @mejo- , 
Just wanted to clarify the scope, since my original request also made reference to files on Nextcloud outside Collectives.
I understand the permission argument for files outside Collectives, but the main goal of this enhancement was about files already in the collective.
In my opinion if the goal is to position Collectives as a "WIKI like" product, then linking (not only for text files)  within one collective should be possible and moving around pages should be handled by the Collective transparently. (either by using stable links or by changing the references)
