### ISSUE TITLE
Page has content but appears as empty (0 bytes) in Files

### ISSUE THREAD

**Issue by jose1711** [nextcloud/collectives#957]
**Describe the bug**
One of my pages contains data but is empty in Files app.

**To Reproduce**
I don't quite remember how I got into this situation but it's quite disturbing.

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 27.1.2
 - Device: Web browser
 - Collectives 2.8.2

Update:
Affected page has id of 55643 and this is a dump of `oc_collectives_pages` table (db is `sqlite3`):
```
sqlite> select * from oc_collectives_pages;
1|55627|jose|||[55699,55697,55681,55643,55641]
2|55641|jose|👶||
3|55643|jose|👸||
4|55681|jose||1697748783|
5|55683|jose|||
6|55697|jose|||
7|55699|jose||1697751148|
```

**Comment by jose1711** [comment]
During night the server got rebooted and suddenly the file in `/var/www/nextcloud/data/appdata_*/collectives/1` that was previously empty now contains actually page data. I might just close it but it would be better to investigate first.

**Comment by mejo-** [comment]
Thanks for the report @jose1711! Usually the text editor should send an autosave request to the server, resulting in writing back the markdown content to the file. If you happen to experience this issue again, please take a look at the browser console  (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> on Firefox/Chrome) and see whether any errors are logged there.

Closing the issue for now due to lack of further information.
